// <auto-generated />
using System;
using System.Text.Json;
using Harmony.Cloud.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Harmony.Cloud.Api.Persistence.Migrations
{
    [DbContext(typeof(CloudDbContext))]
    [Migration("20260727154305_PerDomainSyncTables")]
    partial class PerDomainSyncTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("cloud_revision_seq");

            modelBuilder.Entity("AlbumsEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_albums", (string)null);
                });

            modelBuilder.Entity("ArtistsEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_artists", (string)null);
                });

            modelBuilder.Entity("BlacklistedPlaylistsEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_blacklisted_playlists", (string)null);
                });

            modelBuilder.Entity("FavouritesEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_favourites", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.AlbumRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("BrowseId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("browse_id");

                    b.Property<JsonDocument>("Artists")
                        .HasColumnType("jsonb")
                        .HasColumnName("artists");

                    b.Property<string>("AudioPlaylistId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("audio_playlist_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.Property<string>("Year")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("year");

                    b.HasKey("AccountId", "BrowseId");

                    b.ToTable("cloud_albums", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.ArtistRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("BrowseId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("browse_id");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("RadioId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("radio_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Subscribers")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subscribers");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_url");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "BrowseId");

                    b.ToTable("cloud_artists", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.BlacklistedPlaylistRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("PlaylistId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("playlist_id");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "PlaylistId");

                    b.ToTable("cloud_blacklisted_playlists", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.DeviceEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("app_version");

                    b.Property<bool>("IsRealtimeConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_realtime_connected");

                    b.Property<long>("LastCheckpoint")
                        .HasColumnType("bigint")
                        .HasColumnName("last_checkpoint");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("PushRegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("push_registered_at");

                    b.Property<string>("PushTokenCiphertext")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("push_token_ciphertext");

                    b.Property<bool>("SyncPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("sync_paused");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "DeviceId");

                    b.ToTable("cloud_devices", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.FavouriteRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("VideoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("video_id");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "VideoId");

                    b.ToTable("cloud_favourites", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.PlaybackCommandEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<bool>("Applied")
                        .HasColumnType("boolean")
                        .HasColumnName("applied");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SourceDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_id");

                    b.Property<Guid>("TargetDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_device_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("AccountId", "CommandId");

                    b.HasIndex("AccountId", "TargetDeviceId", "ExpiresAt");

                    b.ToTable("cloud_playback_commands", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.PlaybackSessionEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("CurrentSongId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_song_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("Playing")
                        .HasColumnType("boolean")
                        .HasColumnName("playing");

                    b.Property<long>("PositionMs")
                        .HasColumnType("bigint")
                        .HasColumnName("position_ms");

                    b.Property<DateTimeOffset?>("ProgressUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("progress_updated_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<JsonDocument>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<Guid>("TargetDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_device_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "SessionId");

                    b.HasIndex("AccountId", "EndedAt");

                    b.ToTable("cloud_playback_sessions", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.PlaylistRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("PlaylistId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<bool>("IsCloudPlaylist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cloud_playlist");

                    b.Property<bool>("IsPipedPlaylist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_piped_playlist");

                    b.Property<string>("ItemCount")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("item_count");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "PlaylistId");

                    b.ToTable("cloud_playlists", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.PlaylistSongRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("PlaylistId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("EntryKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_key");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.Property<string>("VideoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("video_id");

                    b.HasKey("AccountId", "PlaylistId", "EntryKey");

                    b.ToTable("cloud_playlist_songs", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.RecentlyPlayedRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("EntryKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_key");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.Property<string>("VideoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("video_id");

                    b.HasKey("AccountId", "EntryKey");

                    b.ToTable("cloud_recently_played", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.SavedSearchRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("EntryKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_key");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Query")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("query");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "EntryKey");

                    b.ToTable("cloud_saved_searches", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.SearchHistoryRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("EntryKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_key");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Query")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("query");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "EntryKey");

                    b.ToTable("cloud_search_history", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.SettingRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "Key");

                    b.ToTable("cloud_settings", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.SongRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("VideoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("video_id");

                    b.Property<JsonDocument>("Album")
                        .HasColumnType("jsonb")
                        .HasColumnName("album");

                    b.Property<JsonDocument>("Artists")
                        .HasColumnType("jsonb")
                        .HasColumnName("artists");

                    b.Property<string>("ArtworkUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("artwork_url");

                    b.Property<long?>("DateMs")
                        .HasColumnType("bigint")
                        .HasColumnName("date_ms");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_s");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.Property<JsonDocument>("TrackDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("track_details");

                    b.Property<string>("Year")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("year");

                    b.HasKey("AccountId", "VideoId");

                    b.ToTable("cloud_songs", (string)null);
                });

            modelBuilder.Entity("PlaylistSongsEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_playlist_songs", (string)null);
                });

            modelBuilder.Entity("PlaylistsEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_playlists", (string)null);
                });

            modelBuilder.Entity("RecentlyPlayedEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_recently_played", (string)null);
                });

            modelBuilder.Entity("SavedSearchesEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_saved_searches", (string)null);
                });

            modelBuilder.Entity("SearchHistoryEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_search_history", (string)null);
                });

            modelBuilder.Entity("SettingsEvent", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('\"cloud_revision_seq\"')");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.ToTable("cloud_events_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
