// <auto-generated />
using System;
using System.Text.Json;
using Harmony.Cloud.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Harmony.Cloud.Api.Persistence.Migrations
{
    [DbContext(typeof(CloudDbContext))]
    partial class CloudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.DeviceEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("app_version");

                    b.Property<bool>("IsRealtimeConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_realtime_connected");

                    b.Property<long>("LastCheckpoint")
                        .HasColumnType("bigint")
                        .HasColumnName("last_checkpoint");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("PushRegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("push_registered_at");

                    b.Property<string>("PushTokenCiphertext")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("push_token_ciphertext");

                    b.Property<bool>("SyncPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("sync_paused");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "DeviceId");

                    b.ToTable("cloud_devices", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.PlaybackCommandEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<bool>("Applied")
                        .HasColumnType("boolean")
                        .HasColumnName("applied");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SourceDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_id");

                    b.Property<Guid>("TargetDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_device_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("AccountId", "CommandId");

                    b.HasIndex("AccountId", "TargetDeviceId", "ExpiresAt");

                    b.ToTable("cloud_playback_commands", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.PlaybackSessionEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("CurrentSongId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_song_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("Playing")
                        .HasColumnType("boolean")
                        .HasColumnName("playing");

                    b.Property<long>("PositionMs")
                        .HasColumnType("bigint")
                        .HasColumnName("position_ms");

                    b.Property<DateTimeOffset?>("ProgressUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("progress_updated_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<JsonDocument>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<Guid>("TargetDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_device_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "SessionId");

                    b.HasIndex("AccountId", "EndedAt");

                    b.ToTable("cloud_playback_sessions", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.SnapshotEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("HlcDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hlc_device_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("tombstone");

                    b.HasKey("AccountId", "EntityType", "EntityId");

                    b.ToTable("cloud_snapshots", (string)null);
                });

            modelBuilder.Entity("Harmony.Cloud.Api.Persistence.SyncEventEntity", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Revision"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HlcLogical")
                        .HasColumnType("integer")
                        .HasColumnName("hlc_logical");

                    b.Property<long>("HlcPhysicalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc_physical_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Revision");

                    b.HasIndex("AccountId", "EventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Revision");

                    b.HasIndex("AccountId", "DeviceId", "DeviceSequence")
                        .IsUnique();

                    b.ToTable("cloud_sync_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
